package agenttb.code.message.domain;

import java.util.Date;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.create_time
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.update_time
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.receivers
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    private String receivers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.state
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.sender_id
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    private String senderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.msg_template_id
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    private Integer msgTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.comment
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.send_type
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    private Integer sendType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.msg_type
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    private Integer msgType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.create_time
     *
     * @return the value of message.create_time
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.create_time
     *
     * @param createTime the value for message.create_time
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.update_time
     *
     * @return the value of message.update_time
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.update_time
     *
     * @param updateTime the value for message.update_time
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.receivers
     *
     * @return the value of message.receivers
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    public String getReceivers() {
        return receivers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.receivers
     *
     * @param receivers the value for message.receivers
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    public void setReceivers(String receivers) {
        this.receivers = receivers == null ? null : receivers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.state
     *
     * @return the value of message.state
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.state
     *
     * @param state the value for message.state
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.sender_id
     *
     * @return the value of message.sender_id
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    public String getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.sender_id
     *
     * @param senderId the value for message.sender_id
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    public void setSenderId(String senderId) {
        this.senderId = senderId == null ? null : senderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.msg_template_id
     *
     * @return the value of message.msg_template_id
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    public Integer getMsgTemplateId() {
        return msgTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.msg_template_id
     *
     * @param msgTemplateId the value for message.msg_template_id
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    public void setMsgTemplateId(Integer msgTemplateId) {
        this.msgTemplateId = msgTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.comment
     *
     * @return the value of message.comment
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.comment
     *
     * @param comment the value for message.comment
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.send_type
     *
     * @return the value of message.send_type
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    public Integer getSendType() {
        return sendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.send_type
     *
     * @param sendType the value for message.send_type
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    public void setSendType(Integer sendType) {
        this.sendType = sendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.msg_type
     *
     * @return the value of message.msg_type
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    public Integer getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.msg_type
     *
     * @param msgType the value for message.msg_type
     *
     * @mbg.generated Thu Jul 25 18:24:38 CST 2019
     */
    public void setMsgType(Integer msgType) {
        this.msgType = msgType;
    }
}