package agenttb.code.message.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class MessageChannelQuery {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message_channel
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message_channel
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message_channel
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_channel
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    public MessageChannelQuery() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_channel
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_channel
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_channel
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_channel
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_channel
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_channel
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_channel
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_channel
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_channel
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_channel
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table message_channel
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andChannelNameIsNull() {
            addCriterion("channel_name is null");
            return (Criteria) this;
        }

        public Criteria andChannelNameIsNotNull() {
            addCriterion("channel_name is not null");
            return (Criteria) this;
        }

        public Criteria andChannelNameEqualTo(String value) {
            addCriterion("channel_name =", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotEqualTo(String value) {
            addCriterion("channel_name <>", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameGreaterThan(String value) {
            addCriterion("channel_name >", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameGreaterThanOrEqualTo(String value) {
            addCriterion("channel_name >=", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameLessThan(String value) {
            addCriterion("channel_name <", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameLessThanOrEqualTo(String value) {
            addCriterion("channel_name <=", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameLike(String value) {
            addCriterion("channel_name like", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotLike(String value) {
            addCriterion("channel_name not like", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameIn(List<String> values) {
            addCriterion("channel_name in", values, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotIn(List<String> values) {
            addCriterion("channel_name not in", values, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameBetween(String value1, String value2) {
            addCriterion("channel_name between", value1, value2, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotBetween(String value1, String value2) {
            addCriterion("channel_name not between", value1, value2, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelUsernameIsNull() {
            addCriterion("channel_username is null");
            return (Criteria) this;
        }

        public Criteria andChannelUsernameIsNotNull() {
            addCriterion("channel_username is not null");
            return (Criteria) this;
        }

        public Criteria andChannelUsernameEqualTo(String value) {
            addCriterion("channel_username =", value, "channelUsername");
            return (Criteria) this;
        }

        public Criteria andChannelUsernameNotEqualTo(String value) {
            addCriterion("channel_username <>", value, "channelUsername");
            return (Criteria) this;
        }

        public Criteria andChannelUsernameGreaterThan(String value) {
            addCriterion("channel_username >", value, "channelUsername");
            return (Criteria) this;
        }

        public Criteria andChannelUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("channel_username >=", value, "channelUsername");
            return (Criteria) this;
        }

        public Criteria andChannelUsernameLessThan(String value) {
            addCriterion("channel_username <", value, "channelUsername");
            return (Criteria) this;
        }

        public Criteria andChannelUsernameLessThanOrEqualTo(String value) {
            addCriterion("channel_username <=", value, "channelUsername");
            return (Criteria) this;
        }

        public Criteria andChannelUsernameLike(String value) {
            addCriterion("channel_username like", value, "channelUsername");
            return (Criteria) this;
        }

        public Criteria andChannelUsernameNotLike(String value) {
            addCriterion("channel_username not like", value, "channelUsername");
            return (Criteria) this;
        }

        public Criteria andChannelUsernameIn(List<String> values) {
            addCriterion("channel_username in", values, "channelUsername");
            return (Criteria) this;
        }

        public Criteria andChannelUsernameNotIn(List<String> values) {
            addCriterion("channel_username not in", values, "channelUsername");
            return (Criteria) this;
        }

        public Criteria andChannelUsernameBetween(String value1, String value2) {
            addCriterion("channel_username between", value1, value2, "channelUsername");
            return (Criteria) this;
        }

        public Criteria andChannelUsernameNotBetween(String value1, String value2) {
            addCriterion("channel_username not between", value1, value2, "channelUsername");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordIsNull() {
            addCriterion("channel_password is null");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordIsNotNull() {
            addCriterion("channel_password is not null");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordEqualTo(String value) {
            addCriterion("channel_password =", value, "channelPassword");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordNotEqualTo(String value) {
            addCriterion("channel_password <>", value, "channelPassword");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordGreaterThan(String value) {
            addCriterion("channel_password >", value, "channelPassword");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("channel_password >=", value, "channelPassword");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordLessThan(String value) {
            addCriterion("channel_password <", value, "channelPassword");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordLessThanOrEqualTo(String value) {
            addCriterion("channel_password <=", value, "channelPassword");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordLike(String value) {
            addCriterion("channel_password like", value, "channelPassword");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordNotLike(String value) {
            addCriterion("channel_password not like", value, "channelPassword");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordIn(List<String> values) {
            addCriterion("channel_password in", values, "channelPassword");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordNotIn(List<String> values) {
            addCriterion("channel_password not in", values, "channelPassword");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordBetween(String value1, String value2) {
            addCriterion("channel_password between", value1, value2, "channelPassword");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordNotBetween(String value1, String value2) {
            addCriterion("channel_password not between", value1, value2, "channelPassword");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterionForJDBCDate("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterionForJDBCDate("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterionForJDBCDate("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterionForJDBCDate("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterionForJDBCDate("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andChannelUrlIsNull() {
            addCriterion("channel_url is null");
            return (Criteria) this;
        }

        public Criteria andChannelUrlIsNotNull() {
            addCriterion("channel_url is not null");
            return (Criteria) this;
        }

        public Criteria andChannelUrlEqualTo(String value) {
            addCriterion("channel_url =", value, "channelUrl");
            return (Criteria) this;
        }

        public Criteria andChannelUrlNotEqualTo(String value) {
            addCriterion("channel_url <>", value, "channelUrl");
            return (Criteria) this;
        }

        public Criteria andChannelUrlGreaterThan(String value) {
            addCriterion("channel_url >", value, "channelUrl");
            return (Criteria) this;
        }

        public Criteria andChannelUrlGreaterThanOrEqualTo(String value) {
            addCriterion("channel_url >=", value, "channelUrl");
            return (Criteria) this;
        }

        public Criteria andChannelUrlLessThan(String value) {
            addCriterion("channel_url <", value, "channelUrl");
            return (Criteria) this;
        }

        public Criteria andChannelUrlLessThanOrEqualTo(String value) {
            addCriterion("channel_url <=", value, "channelUrl");
            return (Criteria) this;
        }

        public Criteria andChannelUrlLike(String value) {
            addCriterion("channel_url like", value, "channelUrl");
            return (Criteria) this;
        }

        public Criteria andChannelUrlNotLike(String value) {
            addCriterion("channel_url not like", value, "channelUrl");
            return (Criteria) this;
        }

        public Criteria andChannelUrlIn(List<String> values) {
            addCriterion("channel_url in", values, "channelUrl");
            return (Criteria) this;
        }

        public Criteria andChannelUrlNotIn(List<String> values) {
            addCriterion("channel_url not in", values, "channelUrl");
            return (Criteria) this;
        }

        public Criteria andChannelUrlBetween(String value1, String value2) {
            addCriterion("channel_url between", value1, value2, "channelUrl");
            return (Criteria) this;
        }

        public Criteria andChannelUrlNotBetween(String value1, String value2) {
            addCriterion("channel_url not between", value1, value2, "channelUrl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table message_channel
     *
     * @mbg.generated do_not_delete_during_merge Fri Jul 26 12:38:07 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table message_channel
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}