package agenttb.code.message.domain;

import java.util.Date;

public class MessageTemplate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_template.id
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_template.template_content
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    private String templateContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_template.template_name
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    private String templateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_template.template_user_id
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    private String templateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_template.state
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_template.create_time
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_template.modify_time
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.id
     *
     * @return the value of message_template.id
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.id
     *
     * @param id the value for message_template.id
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.template_content
     *
     * @return the value of message_template.template_content
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    public String getTemplateContent() {
        return templateContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.template_content
     *
     * @param templateContent the value for message_template.template_content
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    public void setTemplateContent(String templateContent) {
        this.templateContent = templateContent == null ? null : templateContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.template_name
     *
     * @return the value of message_template.template_name
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.template_name
     *
     * @param templateName the value for message_template.template_name
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName == null ? null : templateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.template_user_id
     *
     * @return the value of message_template.template_user_id
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    public String getTemplateUserId() {
        return templateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.template_user_id
     *
     * @param templateUserId the value for message_template.template_user_id
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    public void setTemplateUserId(String templateUserId) {
        this.templateUserId = templateUserId == null ? null : templateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.state
     *
     * @return the value of message_template.state
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.state
     *
     * @param state the value for message_template.state
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.create_time
     *
     * @return the value of message_template.create_time
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.create_time
     *
     * @param createTime the value for message_template.create_time
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_template.modify_time
     *
     * @return the value of message_template.modify_time
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_template.modify_time
     *
     * @param modifyTime the value for message_template.modify_time
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}