package agenttb.code.message.dao;

import java.util.List;

import agenttb.code.message.domain.MessageUser;
import agenttb.code.message.domain.MessageUserQuery;
import org.apache.ibatis.annotations.Param;

public interface MessageUserDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_user
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    long countByExample(MessageUserQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_user
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    int deleteByExample(MessageUserQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_user
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_user
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    int insert(MessageUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_user
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    int insertSelective(MessageUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_user
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    List<MessageUser> selectByExample(MessageUserQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_user
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    MessageUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_user
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    int updateByExampleSelective(@Param("record") MessageUser record, @Param("example") MessageUserQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_user
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    int updateByExample(@Param("record") MessageUser record, @Param("example") MessageUserQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_user
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    int updateByPrimaryKeySelective(MessageUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_user
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    int updateByPrimaryKey(MessageUser record);
}