package agenttb.code.message.dao;

import java.util.List;

import agenttb.code.message.domain.Message;
import agenttb.code.message.domain.MessageQuery;
import org.apache.ibatis.annotations.Param;

public interface MessageDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri Jul 26 12:38:06 CST 2019
     */
    long countByExample(MessageQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri Jul 26 12:38:06 CST 2019
     */
    int deleteByExample(MessageQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri Jul 26 12:38:06 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri Jul 26 12:38:06 CST 2019
     */
    int insert(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri Jul 26 12:38:06 CST 2019
     */
    int insertSelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri Jul 26 12:38:06 CST 2019
     */
    List<Message> selectByExample(MessageQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri Jul 26 12:38:06 CST 2019
     */
    Message selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri Jul 26 12:38:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") Message record, @Param("example") MessageQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri Jul 26 12:38:06 CST 2019
     */
    int updateByExample(@Param("record") Message record, @Param("example") MessageQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri Jul 26 12:38:06 CST 2019
     */
    int updateByPrimaryKeySelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri Jul 26 12:38:06 CST 2019
     */
    int updateByPrimaryKey(Message record);
}