package agenttb.code.message.dao;

import java.util.List;

import agenttb.code.message.domain.MessageRule;
import agenttb.code.message.domain.MessageRuleQuery;
import org.apache.ibatis.annotations.Param;

public interface MessageRuleDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_rule
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    long countByExample(MessageRuleQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_rule
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    int deleteByExample(MessageRuleQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_rule
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_rule
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    int insert(MessageRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_rule
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    int insertSelective(MessageRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_rule
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    List<MessageRule> selectByExample(MessageRuleQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_rule
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    MessageRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_rule
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    int updateByExampleSelective(@Param("record") MessageRule record, @Param("example") MessageRuleQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_rule
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    int updateByExample(@Param("record") MessageRule record, @Param("example") MessageRuleQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_rule
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    int updateByPrimaryKeySelective(MessageRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_rule
     *
     * @mbg.generated Fri Jul 26 12:38:07 CST 2019
     */
    int updateByPrimaryKey(MessageRule record);
}